-- MySQL dump 10.13  Distrib 8.0.36, for Win64 (x86_64)
--
-- Host: db-tech0-gen5-step4-onpremise.mysql.database.azure.com    Database: old_database
-- ------------------------------------------------------
-- Server version	8.0.35

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `vendors`
--

DROP TABLE IF EXISTS `vendors`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `vendors` (
  `vendor_id` int NOT NULL AUTO_INCREMENT,
  `company_name` varchar(255) NOT NULL,
  `email_address` varchar(255) NOT NULL,
  `address` text NOT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `registration_date` date NOT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`vendor_id`)
) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `vendors`
--

LOCK TABLES `vendors` WRITE;
/*!40000 ALTER TABLE `vendors` DISABLE KEYS */;
INSERT INTO `vendors` VALUES (25,'Lopez and Sons','smithjose@wilson.com','7859 Eric Mall\nNelsonmouth, MS 23373','Reginald Jones','2023-08-19','6599027473','Generated by Faker.'),(26,'Murphy, Estrada and Haney','valenzuelasean@brooks-blackwell.com','29821 Lopez Groves\nWest Isaac, HI 53917','Sharon Roberts','2023-02-27','(361)571-8508x8333','Generated by Faker.'),(27,'Bryant-Hunter','walkerjennifer@owens-ward.com','87363 Haley Way\nMillerberg, ME 01271','Tina Landry','2022-04-08','001-857-424-0812x802','Generated by Faker.'),(28,'Robinson-Green','russell82@perry.com','470 Castro Well Suite 748\nJennytown, VA 47378','Michael Christensen','2022-04-05','218.456.5209x84877','Generated by Faker.'),(29,'Gonzalez-Bauer','andrewprice@quinn-briggs.com','7700 Sullivan Green Apt. 716\nJessicamouth, VI 28368','Daisy Woods','2023-04-25','301-702-9382x77890','Generated by Faker.'),(30,'Zimmerman-Walker','diazdaniel@baker.com','747 Lisa Lakes Suite 400\nSouth Rachel, MP 05515','Brianna Griffith','2022-04-10','001-982-918-9832x995','Generated by Faker.'),(31,'Osborne Ltd','williamsmason@smith.com','3593 Day Ranch\nPort Jennifer, ID 32102','Kellie Jones','2022-08-14','(372)837-8421','Generated by Faker.'),(32,'Aguirre-Robertson','justinroberts@king.com','40222 Nicole Loop\nEast Shellyborough, NC 32827','Sonia Parker','2022-08-11','303.642.5184x81548','Generated by Faker.'),(33,'Cardenas, Cox and Garza','butlerrachel@brown-wright.info','39362 Rodriguez Green\nLake Juanfurt, VT 32294','Christine Hernandez','2023-09-12','722.675.1727x635','Generated by Faker.'),(34,'Martinez, Young and Kelly','melissa66@turner.com','2636 Wendy Shoal Suite 420\nEast Andrea, MN 79094','Shawn Sparks','2022-04-20','+1-439-945-7474x1316','Generated by Faker.'),(35,'Smith Inc','amber15@clements.net','2293 Gregory Prairie\nSouth Jamie, TX 45442','Jennifer Reed','2022-03-29','459.873.0093','Generated by Faker.'),(36,'Jackson-Hays','brittneyrowe@mcguire-boyer.net','901 Sparks Springs\nNew Leslie, ND 49006','Elizabeth Miller','2024-02-21','001-897-387-1865x969','Generated by Faker.'),(37,'Dixon Inc','rosebrian@roman-pitts.com','00913 Shelly Square Apt. 386\nBrianmouth, DC 26977','Joseph Beard','2022-12-14','001-592-263-7115x261','Generated by Faker.'),(38,'Davis Ltd','holmesfrank@copeland.info','766 Patricia Alley Apt. 657\nDanielschester, OK 52104','Christopher Stewart','2022-08-30','869.931.7411','Generated by Faker.'),(39,'Hurley PLC','jasonwalker@white.com','USCGC Mueller\nFPO AE 32112','Joel Smith','2022-11-24','467-523-9095x6264','Generated by Faker.'),(40,'Brady, Mckee and Porter','farleyrebecca@rodgers.com','390 Hannah Walk\nLake Kristymouth, WA 36422','Theresa Parker','2024-01-20','527-334-1736','Generated by Faker.'),(41,'Robinson-Walker','katherine14@peterson-vincent.com','45914 Faith Lakes Suite 426\nNorth Summertown, MO 49122','Gilbert Clark','2022-12-16','660-411-1402x006','Generated by Faker.'),(42,'Robinson, Williams and Walker','olane@brown.com','999 Smith Route Suite 261\nVillamouth, AR 60303','Jeffrey Hardy','2023-05-10','953-211-9856x00032','Generated by Faker.'),(43,'Ramirez-Palmer','ycasey@cook-cannon.org','38557 Diaz Neck Suite 700\nNew Sandra, IL 06486','Kimberly Ramirez','2022-06-09','001-926-342-2622x728','Generated by Faker.'),(44,'Miller LLC','fhoward@king.com','1081 Hernandez Lodge\nNew Brianport, PA 57278','Priscilla Ruiz','2023-07-14','001-349-373-1784x990','Generated by Faker.'),(45,'Smith, Nguyen and Delgado','sellersdenise@stewart-patel.info','768 Gray Shores Apt. 545\nClarkemouth, MI 79777','Wendy Meyer','2024-01-24','001-203-515-5123x238','Generated by Faker.'),(46,'Kline-Perez','ocollins@foster.info','770 Dana Pike Suite 143\nWest Rebeccaville, DC 95681','Jason Jenkins','2022-05-30','429.668.7151x1728','Generated by Faker.'),(47,'Baker Inc','racheljackson@harrington.com','9974 Ortega Passage\nSheilaton, LA 28227','Shane Wright','2023-01-16','001-645-505-8190x396','Generated by Faker.'),(48,'Beasley Inc','shellybaxter@fowler.com','3712 Murray Field Apt. 776\nEast Lukeland, OH 77551','Robert Santos','2023-03-29','(636)242-8428x624','Generated by Faker.'),(49,'Sanders, Smith and Gonzalez','thomas04@ortiz.info','218 Gary Causeway Suite 893\nDavisstad, NE 35562','Lauren Osborne','2023-01-17','756.899.5721x914','Generated by Faker.'),(50,'Zimmerman, Schneider and Taylor','jacobmurphy@baxter.org','00259 Ware Curve Apt. 562\nClaudiahaven, AR 63108','Rebecca Rodriguez','2023-07-24','484.901.0440x283','Generated by Faker.'),(51,'Contreras, Rodriguez and Horne','ymorris@banks-jackson.com','43929 Jason Avenue\nMooremouth, MO 03597','Tiffany Murillo','2022-06-25','9092180906','Generated by Faker.'),(52,'Steele and Sons','bbaird@knapp.com','43872 Kaitlyn Burg Apt. 586\nJeffreyshire, PA 67620','Linda Ramirez','2022-08-11','869-208-9585','Generated by Faker.'),(53,'Gordon, Cooper and Cuevas','robinsonapril@mullins-vega.com','10705 Betty Bridge Suite 984\nDaltonchester, CA 65089','Michael Reid','2023-10-23','(741)808-1584x24823','Generated by Faker.'),(54,'Hahn-Wilson','julieperry@chen.com','PSC 0312, Box 7143\nAPO AE 39033','William Griffin','2023-04-20','873.699.8245x0516','Generated by Faker.'),(55,'Graves-King','zbrady@lee-aguirre.com','1937 Antonio Lights Apt. 602\nNew Elizabeth, VT 38842','Kyle Williams','2024-01-15','+1-575-978-3207x266','Generated by Faker.'),(56,'Williams LLC','dstein@perry-mendez.biz','11671 Deleon Crossing\nWilliamsstad, ND 40243','Michael Miller','2022-07-31','864.583.4048x88529','Generated by Faker.'),(57,'Wilson-Cook','faulknerstephanie@bowers.net','8317 Melvin Highway Suite 576\nPort John, CA 00906','Christopher Walters','2023-09-30','668.615.7804x2467','Generated by Faker.'),(58,'Trevino, Benson and Owen','hpearson@jackson-nichols.com','9863 Pena Forge Suite 926\nLake Anthony, GU 90233','Tammy Brown','2024-02-22','001-311-986-7574','Generated by Faker.'),(59,'Simpson Ltd','mcculloughwilliam@ramsey.org','813 Hernandez Turnpike\nPowellville, WA 82869','Cynthia Wilkerson','2023-01-03','598.464.3276x73238','Generated by Faker.'),(60,'Chavez-Bell','xsparks@floyd.org','Unit 0475 Box 8218\nDPO AP 47143','Amy Shaw','2023-11-28','(775)782-2489x322','Generated by Faker.'),(61,'Vang, King and Cole','tara64@horne-parker.com','2531 Michael Plaza Suite 026\nCarlshire, NV 82090','Michael Stephens','2024-02-25','993-854-9559x409','Generated by Faker.'),(62,'Parker-Nielsen','virginia61@moore.org','30234 Mays Radial Suite 640\nPort Chelseaville, MS 76410','Tina Ingram DDS','2024-03-03','445-605-0699','Generated by Faker.'),(63,'Graham-Burgess','pfleming@thomas.com','81429 Ashley Wall Apt. 836\nNicoleburgh, CA 66673','Jessica Ortiz','2023-02-12','001-266-417-4056x008','Generated by Faker.'),(64,'Parrish, Hernandez and Hunter','nblack@jordan.com','50998 Ashley Walks Apt. 295\nTaylorstad, MD 08385','Bonnie Coleman','2024-01-03','8299536345','Generated by Faker.'),(65,'Martinez, Wood and Walton','foxdaniel@petersen-barr.org','Unit 3728 Box 2868\nDPO AA 40245','Robert Green','2022-10-18','(934)879-3090','Generated by Faker.'),(66,'Farmer and Sons','jeffrey62@anderson.com','89628 Mathis Parks Apt. 402\nWrightburgh, SC 50026','Paula Moses DDS','2023-11-14','482.751.2050x3500','Generated by Faker.'),(67,'Rodriguez-Anderson','guzmanzachary@davis-turner.com','004 Chen Ranch Suite 660\nNew Sherry, WA 59886','Vanessa Johnson','2023-05-23','204.701.6554','Generated by Faker.'),(68,'Campbell-Marshall','parsonsalbert@newman.biz','069 Anderson Extensions Apt. 311\nNorth Calvinfurt, CA 11832','Heidi Vincent','2022-11-05','001-517-615-9479x425','Generated by Faker.'),(69,'Sheppard, Murphy and Melendez','kenneth54@rodriguez-hatfield.biz','7351 Burke Junctions\nEast Samuel, PA 06835','Andrew Austin','2022-04-21','(852)269-7658x9732','Generated by Faker.'),(70,'Fischer PLC','kennedykelly@cochran.com','069 Karen Plaza Suite 615\nSouth Katie, HI 80208','Zachary Wood','2023-04-19','763.599.6548','Generated by Faker.'),(71,'Rodriguez Inc','davidsmith@gilbert-payne.biz','313 Adam Orchard Apt. 537\nEast Robert, NJ 92473','Ian Wells','2022-09-11','+1-747-653-3352x4757','Generated by Faker.'),(72,'Morales-Hubbard','simsjames@johnson-hayden.com','9379 Natalie Circles\nNew Jamesland, RI 35561','Mr. Douglas Lewis','2022-12-06','+1-230-648-2686x633','Generated by Faker.'),(73,'Miller-Elliott','amandadavis@vargas-glenn.info','795 Wilkinson Roads\nWest Erik, NE 29121','Sheila Brock','2023-06-22','612.423.0637','Generated by Faker.'),(74,'Barr, Christian and Vega','craig88@peterson.net','4368 Angela Pike Suite 193\nCharlesberg, NV 90106','Janet Parker MD','2023-06-28','001-525-977-3852x855','Generated by Faker.');
/*!40000 ALTER TABLE `vendors` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2024-03-22  3:28:19
